Repository SpeiserK/Group-C---Camp-OAC, pull requests merged in 2022-10, with the labels that each got.

#17 Tech stack
  Documents/Requirements_Report.md
Labels: Chore

#18 Updated level 1 DFD
  Documents/Requirements_Report.md
Labels: Chore

#20 Requirements report research
  Documents/Requirements_Report.md
  Minutes/Client Minutes/Client meeting #3 Oct3.pdf
  Minutes/Scrum Minutes/Scrum meeting #2 Oct3.pdf
Labels: documentation, Exploration

#22 Add to tech stack, mostly back-end revisions
  Documents/Requirements_Report.md
Labels: Exploration

#24 Requirements_report formatting
  Documents/Requirements_Report.md
Labels: Chore

#29 update requirementreport;
  Documents/Requirements_Report.md
Labels: Chore

#31 Report review
  Documents/Camp OAC DFD lvl1.jpeg
  Documents/Requirements_Report.md
  images/Camp OAC DFD lvl0.png
Labels: Chore

#34 turn lvl1 dfd to png
  Documents/Requirements_Report.md
  images/Camp OAC DFD lvl1.jpeg
  images/Camp OAC DFD lvl1.png
Labels: Chore

#35 Fix DFD lvl1 image in req_report final
  Documents/Requirements_Report.md
Labels: Chore

#38 Create Scrum Meeting #3 Oct10.pdf
  Minutes/Scrum Minutes/Scrum Meeting #3 Oct10.pdf
Labels: documentation

#40 Added the Requirements Report slides to the Media folder
  Media/Camp-OAC-GroupC-RequirementsReport.pptx
Labels: Task

#47 Minutes added for OCT 17
  Minutes/Client Minutes/Client meeting #4 Oct17.pdf
  Minutes/Scrum Minutes/Scrum Meeting #4 Oct17.pdf
Labels: documentation

#51 Updated the requirements report
  Documents/Requirements_Report.md
Labels: Task

#53 Finish tech stack section
  Documents/Requirements_Report.md
  Media/images/TechStackTable.png
Labels: Task

#68 Added logo
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/image2vector.svg
Labels: Task

#78 Added Gantt chart
  README.md
Labels: Chore

#82 Frontend karlen
  MERN Scripts/mern-emsystem/package-lock.json
  MERN Scripts/mern-emsystem/package.json
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/components/Logo.js
  MERN Scripts/mern-emsystem/src/components/Navbar.js
  MERN Scripts/mern-emsystem/src/components/Textbox.js
  MERN Scripts/mern-emsystem/src/components/image2vector.svg
  MERN Scripts/mern-emsystem/src/image2vector.svg
  MERN Scripts/mern-emsystem/src/index.js
  MERN Scripts/mern-emsystem/src/logo.svg
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Task
