Repository SpeiserK/Group-C---Camp-OAC, pull requests merged in 2022-11, with the labels that each got.

#86 Added text box for firewood input
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/hooks/toggleClick.js
  MERN Scripts/mern-emsystem/src/components/usables/EmailCheck.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
Labels: Task

#87 Delete Location.JS
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/components/LocationsList.js
  MERN Scripts/mern-emsystem/src/pages/Location.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Chore

#95 Progress bar
  MERN Scripts/backend/models.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Progressbar.js
Labels: Exploration

#96 Created email check function
  MERN Scripts/mern-emsystem/package-lock.json
  MERN Scripts/mern-emsystem/package.json
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/hooks/matchEmail.js
  MERN Scripts/mern-emsystem/src/components/usables/EmailCheck.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Task

#98 Submit button now links to order page
  MERN Scripts/mern-emsystem/src/components/hooks/matchEmail.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
Labels: Task

#101 Frontend work
  MERN Scripts/mern-emsystem/src/components/LocationsList.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
Labels: Chore

#104 finish payment page, ready to work
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
Labels: Chore

#105 PlaceOrder error checking
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
  MERN Scripts/mern-emsystem/src/components/hooks/toggleClick.js
Labels: Task

#107 Order qty input handling
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
Labels: Task

#114 Fixed order input box
  MERN Scripts/mern-emsystem/src/components/LocationsList.js
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
Labels: Task

#117 add Futiger and OpenSans fonts
  MERN Scripts/backend/package.json
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Banner.js
  MERN Scripts/mern-emsystem/src/fonts/Frutiger/Frutiger.ttf
  MERN Scripts/mern-emsystem/src/fonts/Frutiger/Frutiger_bold.ttf
  MERN Scripts/mern-emsystem/src/fonts/OpenSans/OpenSans-Regular.ttf
  MERN Scripts/mern-emsystem/src/index.js
Labels: Chore

#118 CSS styling on startpage
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Banner.js
  MERN Scripts/mern-emsystem/src/components/Navbar.js
  MERN Scripts/mern-emsystem/src/components/hooks/matchEmail.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Task

#122 Order page styling
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/hooks/matchEmail.js
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
Labels: Chore

#127 Dropdown fr
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Banner.js
  MERN Scripts/mern-emsystem/src/components/Dropdown.js
Labels: Chore

#135 Emp pages
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/components/EmpTools.js
  MERN Scripts/mern-emsystem/src/pages/Emp.js
  MERN Scripts/mern-emsystem/src/pages/Inventory.js
  MERN Scripts/mern-emsystem/src/pages/OrderHistory.js
  MERN Scripts/mern-emsystem/src/pages/ViewOrders.js
Labels: Chore

#139 Dropdown work
  MERN Scripts/mern-emsystem/package-lock.json
  MERN Scripts/mern-emsystem/package.json
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Banner.js
  MERN Scripts/mern-emsystem/src/components/Dropdown.js
  MERN Scripts/mern-emsystem/src/components/Progressbar.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Task

#147 Button styling on EmpTools
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/EmpTools.js
  MERN Scripts/package.json
Labels: Chore

#148 About and fonts
  MERN Scripts/backend/package.json
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/components/Dropdown.js
  MERN Scripts/mern-emsystem/src/fonts/Georgia/Georgia.ttf
  MERN Scripts/mern-emsystem/src/fonts/Sentienl/FontsFree-Net-Sentinel-Medium.ttf
  MERN Scripts/mern-emsystem/src/index.css
  MERN Scripts/mern-emsystem/src/pages/About.js
Labels: Task

#155 About and fonts
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Banner.js
  MERN Scripts/mern-emsystem/src/components/Dropdown.js
  MERN Scripts/mern-emsystem/src/components/PaymentSummary.js
  MERN Scripts/mern-emsystem/src/components/hooks/matchEmail.js
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
  MERN Scripts/mern-emsystem/src/pages/About.js
  MERN Scripts/mern-emsystem/src/pages/CashConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/ETransferConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Task

#161 Create and show progress bar
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Banner.js
  MERN Scripts/mern-emsystem/src/components/Dropdown.js
  MERN Scripts/mern-emsystem/src/components/OurProgBar.js
  MERN Scripts/mern-emsystem/src/components/Progressbar.js
  MERN Scripts/mern-emsystem/src/pages/CashConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/ETransferConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
  MERN Scripts/mern-emsystem/src/pages/SquareConfirmation.js
Labels: Task

#162 Inventory by location feature
  MERN Scripts/backend/routes/OrderRoute.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/hooks/InvByLoc.js
  MERN Scripts/mern-emsystem/src/pages/Inventory.js
Labels: Task
