Repository SpeiserK/Group-C---Camp-OAC, pull requests merged in 2023-03, with the labels that each got.

#289 For error handling Improvements
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
Labels: Exploration

#291 Payment styling
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/components/Banner.js
  MERN Scripts/mern-emsystem/src/components/Logo.js
  MERN Scripts/mern-emsystem/src/components/PaymentSummary.js
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
  MERN Scripts/mern-emsystem/src/pages/About.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Task

#299 Payment details frontend
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/components/Banner.js
  MERN Scripts/mern-emsystem/src/components/Dropdown.js
  MERN Scripts/mern-emsystem/src/components/customerSide/CustomerHistory.js
  MERN Scripts/mern-emsystem/src/pages/About.js
  MERN Scripts/mern-emsystem/src/pages/CashConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/CustOrderHist.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
  MERN Scripts/mern-emsystem/src/pages/SquareReceipt.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Task

#301 Payment details frontend
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/PaymentSummary.js
  MERN Scripts/mern-emsystem/src/components/customerSide/CustomerHistory.js
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
  MERN Scripts/mern-emsystem/src/pages/CashConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/CustOrderHist.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
  MERN Scripts/mern-emsystem/src/pages/SquareReceipt.js
Labels: Chore

#305 Admin css
  MERN Scripts/backend/routes/OrderRoute.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Empbanner.js
  MERN Scripts/mern-emsystem/src/components/LocationManagement.js
  MERN Scripts/mern-emsystem/src/components/Signup/EmpSignup.js
  MERN Scripts/mern-emsystem/src/pages/CustOrderHist.js
  MERN Scripts/mern-emsystem/src/pages/Emp.js
  MERN Scripts/mern-emsystem/src/pages/OrderHistory.js
  MERN Scripts/mern-emsystem/src/pages/SuperAdmin.js
Labels: Chore

#312 Order hist search from adminCss branch
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/OrderDispHist.js
  MERN Scripts/mern-emsystem/src/components/location/locationSelect.js
  MERN Scripts/mern-emsystem/src/pages/Emp.js
  MERN Scripts/mern-emsystem/src/pages/OrderHistory.js
Labels: Task

#331 Error styling
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
Labels: Exploration

#333 Css cleaner
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Bundles2.js
  MERN Scripts/mern-emsystem/src/components/OrderLiveDisp.js
  MERN Scripts/mern-emsystem/src/components/customerSide/CustomerHistory.js
  MERN Scripts/mern-emsystem/src/components/hooks/placeOrder.js
  MERN Scripts/mern-emsystem/src/pages/CustOrderHist.js
  MERN Scripts/mern-emsystem/src/pages/Emp.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Chore
