Repository SpeiserK/Group-C---Camp-OAC, pull requests merged in 2023-01, with the labels that each got.

#183 A branch wants to merge, add date/time to order schema + CSS changes
  MERN Scripts/backend/models.js
  MERN Scripts/backend/routes/OrderRoute.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Bundles2.js
  MERN Scripts/mern-emsystem/src/components/CampLogo.js
  MERN Scripts/mern-emsystem/src/components/CampName.js
  MERN Scripts/mern-emsystem/src/components/FirewoodTeam.js
  MERN Scripts/mern-emsystem/src/components/Navbar.js
  MERN Scripts/mern-emsystem/src/components/OrderDispHist.js
  MERN Scripts/mern-emsystem/src/components/OrderLiveDisp.js
  MERN Scripts/mern-emsystem/src/components/hooks/matchEmail.js
  MERN Scripts/mern-emsystem/src/components/pictures/Camp-OAC-Logo-Secondary.png
  MERN Scripts/mern-emsystem/src/components/pictures/Camp-OAC-Logo_WordMark-Light.png
  MERN Scripts/mern-emsystem/src/pages/About.js
  MERN Scripts/mern-emsystem/src/pages/CashConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/ETransferConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/Orderqty.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
  MERN Scripts/mern-emsystem/src/pages/SquareConfirmation.js
  MERN Scripts/mern-emsystem/src/pages/Startpage.js
Labels: Task

#187 Update README
  README.md
Labels: Task

#193 Update gitIgnore
  .gitignore
Labels: Chore

#192 Add price and payment type to DB
  MERN Scripts/backend/models.js
  MERN Scripts/backend/routes/OrderRoute.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/OrderDispHist.js
  MERN Scripts/mern-emsystem/src/components/OrderLiveDisp.js
  MERN Scripts/mern-emsystem/src/pages/Payment.js
Labels: Chore

#197 Card Payment templates
  MERN Scripts/backend/package-lock.json
  MERN Scripts/backend/package.json
  MERN Scripts/backend/routes/pay.js
  MERN Scripts/mern-emsystem/package-lock.json
  MERN Scripts/mern-emsystem/package.json
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/SquareForm.js
Labels: Exploration

#199 Square Pay Form
  MERN Scripts/mern-emsystem/src/.env
  MERN Scripts/mern-emsystem/src/App.js
  MERN Scripts/mern-emsystem/src/components/SquareForm.js
  MERN Scripts/mern-emsystem/src/next.config.js
  MERN Scripts/mern-emsystem/src/pages/SquarePay.js
  MERN Scripts/mern-emsystem/src/pages/api/pay.js
Labels: Exploration

#211 Payment details
  MERN Scripts/backend/models.js
  MERN Scripts/backend/routes/OrderRoute.js
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/package-lock.json
  MERN Scripts/mern-emsystem/package.json
  MERN Scripts/mern-emsystem/src/components/LocationLiveDisp.js
  MERN Scripts/mern-emsystem/src/components/OrderDispHist.js
  MERN Scripts/mern-emsystem/src/components/OrderLiveDisp.js
  MERN Scripts/mern-emsystem/src/pages/Emp.js
Labels: Task

#218 Pickup function
  MERN Scripts/backend/routes/OrderRoute.js
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/App.css
  MERN Scripts/mern-emsystem/src/components/Navbar.js
  MERN Scripts/mern-emsystem/src/components/OrderDispHist.js
  MERN Scripts/mern-emsystem/src/components/OrderLiveDisp.js
Labels: Task

#227 Node mailer
  MERN Scripts/backend/package-lock.json
  MERN Scripts/backend/package.json
  MERN Scripts/backend/routes/OrderRoute.js
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/components/OrderLiveDisp.js
  README.md
Labels: Exploration

#237 Square progress
  MERN Scripts/backend/routes/api/charge.js
  MERN Scripts/backend/routes/api/pay.js
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/components/SquareCheck.js
  MERN Scripts/mern-emsystem/src/components/SquareForm.js
  MERN Scripts/mern-emsystem/src/pages/SquarePay.js
Labels: Exploration

#233 Email Details
  MERN Scripts/backend/routes/OrderRoute.js
  MERN Scripts/backend/server.js
  MERN Scripts/mern-emsystem/src/components/OrderDispHist.js
  MERN Scripts/mern-emsystem/src/components/OrderLiveDisp.js
Labels: Chore
